//
// AchievementsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AchievementsAPI {

    /**
     Get achievements by member reference id
     
     - parameter achievementRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAchievements(achievementRequest: AchievementRequest, apiResponseQueue: DispatchQueue = OpenAPIClient.apiResponseQueue, completion: @escaping ((_ data: AchievementResponse?, _ error: Error?) -> Void)) {
        getAchievementsWithRequestBuilder(achievementRequest: achievementRequest).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get achievements by member reference id
     - POST /achievements
     - Returns a list of achievements for the provided member ref id and applied filters.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter achievementRequest: (body)  
     - returns: RequestBuilder<AchievementResponse> 
     */
    open class func getAchievementsWithRequestBuilder(achievementRequest: AchievementRequest) -> RequestBuilder<AchievementResponse> {
        let localVariablePath = "/achievements"
        let localVariableURLString = OpenAPIClient.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: achievementRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AchievementResponse>.Type = OpenAPIClient.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
