basePackage: com.ziqni.gamification.client
configPackage: com.ziqni.gamification.client.config
apiPackage: com.ziqni.gamification.client.api
modelPackage: com.ziqni.gamification.client.model
groupId: com.ziqni
artifactId: ziqni-gamification-api-client
dateLibrary: java8
hideGenerationTimestamp: true
files:
  ApiClientFactoryWs.mustache:
    folder: src/main/java/com/ziqni/gamification/client
    templateType: SupportingFiles
    destinationFilename: ApiClientFactoryWs.java
  api-ws-client.mustache:
    templateType: API
    destinationFilename: Ws.java