/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.gamification.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.*;

/**
 * Model tests for DependantOn
 */
public class DependantOnTest {
    private final DependantOn model = new DependantOn();

    /**
     * Model tests for DependantOn
     */
    @Test
    public void testDependantOn() {
        // TODO: test DependantOn
    }

    /**
     * Test the property 'must'
     */
    @Test
    public void mustTest() {
        // TODO: test must
    }

    /**
     * Test the property 'mustNot'
     */
    @Test
    public void mustNotTest() {
        // TODO: test mustNot
    }

    /**
     * Test the property 'should'
     */
    @Test
    public void shouldTest() {
        // TODO: test should
    }

    /**
     * Test the property 'shouldMatchAtLeast'
     */
    @Test
    public void shouldMatchAtLeastTest() {
        // TODO: test shouldMatchAtLeast
    }

}
