/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.gamification.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.*;

/**
 * Model tests for QueryMultipleFields
 */
public class QueryMultipleFieldsTest {
    private final QueryMultipleFields model = new QueryMultipleFields();

    /**
     * Model tests for QueryMultipleFields
     */
    @Test
    public void testQueryMultipleFields() {
        // TODO: test QueryMultipleFields
    }

    /**
     * Test the property 'queryFields'
     */
    @Test
    public void queryFieldsTest() {
        // TODO: test queryFields
    }

    /**
     * Test the property 'queryValue'
     */
    @Test
    public void queryValueTest() {
        // TODO: test queryValue
    }

}
