/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.gamification.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ziqni.gamification.client.model.EntityType;
import com.ziqni.gamification.client.model.RewardTypeReduced;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.*;

/**
 * Model tests for Reward
 */
public class RewardTest {
    private final Reward model = new Reward();

    /**
     * Model tests for Reward
     */
    @Test
    public void testReward() {
        // TODO: test Reward
    }

    /**
     * Test the property 'entityType'
     */
    @Test
    public void entityTypeTest() {
        // TODO: test entityType
    }

    /**
     * Test the property 'entityId'
     */
    @Test
    public void entityIdTest() {
        // TODO: test entityId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'rewardRank'
     */
    @Test
    public void rewardRankTest() {
        // TODO: test rewardRank
    }

    /**
     * Test the property 'rewardValue'
     */
    @Test
    public void rewardValueTest() {
        // TODO: test rewardValue
    }

    /**
     * Test the property 'rewardType'
     */
    @Test
    public void rewardTypeTest() {
        // TODO: test rewardType
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'issueLimit'
     */
    @Test
    public void issueLimitTest() {
        // TODO: test issueLimit
    }

    /**
     * Test the property 'delay'
     */
    @Test
    public void delayTest() {
        // TODO: test delay
    }

    /**
     * Test the property 'pointInTime'
     */
    @Test
    public void pointInTimeTest() {
        // TODO: test pointInTime
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'constraints'
     */
    @Test
    public void constraintsTest() {
        // TODO: test constraints
    }

}
