/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZiqniMemberApi);
  }
}(this, function(expect, ZiqniMemberApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZiqniMemberApi.LeaderboardSubscriptionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LeaderboardSubscriptionRequest', function() {
    it('should create an instance of LeaderboardSubscriptionRequest', function() {
      // uncomment below and update the code to test LeaderboardSubscriptionRequest
      //var instance = new ZiqniMemberApi.LeaderboardSubscriptionRequest();
      //expect(instance).to.be.a(ZiqniMemberApi.LeaderboardSubscriptionRequest);
    });

    it('should have the property leaderboardFilter (base name: "leaderboardFilter")', function() {
      // uncomment below and update the code to test the property leaderboardFilter
      //var instance = new ZiqniMemberApi.LeaderboardSubscriptionRequest();
      //expect(instance).to.be();
    });

    it('should have the property entityId (base name: "entityId")', function() {
      // uncomment below and update the code to test the property entityId
      //var instance = new ZiqniMemberApi.LeaderboardSubscriptionRequest();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instance = new ZiqniMemberApi.LeaderboardSubscriptionRequest();
      //expect(instance).to.be();
    });

  });

}));
