/**
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZiqniTechGamificationApiClient);
  }
}(this, function(expect, ZiqniTechGamificationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZiqniTechGamificationApiClient.MemberAllOf();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberAllOf', function() {
    it('should create an instance of MemberAllOf', function() {
      // uncomment below and update the code to test MemberAllOf
      //var instance = new ZiqniTechGamificationApiClient.MemberAllOf();
      //expect(instance).to.be.a(ZiqniTechGamificationApiClient.MemberAllOf);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ZiqniTechGamificationApiClient.MemberAllOf();
      //expect(instance).to.be();
    });

    it('should have the property memberRefId (base name: "memberRefId")', function() {
      // uncomment below and update the code to test the property memberRefId
      //var instance = new ZiqniTechGamificationApiClient.MemberAllOf();
      //expect(instance).to.be();
    });

    it('should have the property memberType (base name: "memberType")', function() {
      // uncomment below and update the code to test the property memberType
      //var instance = new ZiqniTechGamificationApiClient.MemberAllOf();
      //expect(instance).to.be();
    });

    it('should have the property teamMembers (base name: "teamMembers")', function() {
      // uncomment below and update the code to test the property teamMembers
      //var instance = new ZiqniTechGamificationApiClient.MemberAllOf();
      //expect(instance).to.be();
    });

    it('should have the property constraints (base name: "constraints")', function() {
      // uncomment below and update the code to test the property constraints
      //var instance = new ZiqniTechGamificationApiClient.MemberAllOf();
      //expect(instance).to.be();
    });

    it('should have the property timeZoneOffset (base name: "timeZoneOffset")', function() {
      // uncomment below and update the code to test the property timeZoneOffset
      //var instance = new ZiqniTechGamificationApiClient.MemberAllOf();
      //expect(instance).to.be();
    });

  });

}));
