/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.gamification.client.api;

import com.auth0.jwt.JWT;
import com.auth0.jwt.interfaces.DecodedJWT;
import com.ziqni.gamification.client.ApiClientFactory;
import com.ziqni.gamification.client.ApiException;
import com.ziqni.gamification.client.model.*;
import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * API tests for TokenApi
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class TokenApiTest implements tests.utils.CompleteableFutureTestWrapper{

    private final TokenApi api;

    public TokenApiTest() {
        this.api = ApiClientFactory.getTokenApi();
    }

    /**
     * 
     *
     * Get Jwt Token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMemberSessionTokenTest() throws ApiException {
        TokenRequest tokenRequest = new TokenRequest()
                .apiKey("2c90c068a8319a4503a9fc0addc48501")
                .expires(60)
                .isReferenceId(true)
                .member("100015619");

        TokenResponse response = api.getToken(tokenRequest).join();

        assertNotNull(response.getData());

        DecodedJWT jwt = JWT.decode(response.getData().getJwtToken());
        assertNotNull(jwt);
        assertEquals("100015619",jwt.getClaims().get("member_reference_id").asString());
    }

    /**
     *
     *
     * Get Jwt Token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPublicSessionTokenTest() throws ApiException {
        TokenRequest tokenRequest = new TokenRequest()
//                .apiKey("2c90c068a8319a4503a9fc0addc48501")
                .apiKey("b69bc598abcfaa48f6a9b39a2d8bddbe")
                .expires(600)
                .isReferenceId(false)
                .member("PUBLIC");

        TokenResponse response = api.getToken(tokenRequest).join();

        assertNotNull(response.getData());

        DecodedJWT jwt = JWT.decode(response.getData().getJwtToken());
        assertNotNull(jwt);
        assertEquals("PUBLIC",jwt.getClaims().get("member_reference_id").asString());
    }
    
}
