/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionTypeAdjustmentFactor model module.
 * @module model/ActionTypeAdjustmentFactor
 * @version 1.0.17
 */
class ActionTypeAdjustmentFactor {
    /**
     * Constructs a new <code>ActionTypeAdjustmentFactor</code>.
     * @alias module:model/ActionTypeAdjustmentFactor
     * @param adjustmentFactor {Number} The multiplier to apply to source values received for this product events
     * @param actionTypeId {String} A unique system generated identifier for Action Type
     */
    constructor(adjustmentFactor, actionTypeId) { 
        
        ActionTypeAdjustmentFactor.initialize(this, adjustmentFactor, actionTypeId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, adjustmentFactor, actionTypeId) { 
        obj['adjustmentFactor'] = adjustmentFactor;
        obj['actionTypeId'] = actionTypeId;
    }

    /**
     * Constructs a <code>ActionTypeAdjustmentFactor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionTypeAdjustmentFactor} obj Optional instance to populate.
     * @return {module:model/ActionTypeAdjustmentFactor} The populated <code>ActionTypeAdjustmentFactor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionTypeAdjustmentFactor();

            if (data.hasOwnProperty('adjustmentFactor')) {
                obj['adjustmentFactor'] = ApiClient.convertToType(data['adjustmentFactor'], 'Number');
            }
            if (data.hasOwnProperty('actionTypeId')) {
                obj['actionTypeId'] = ApiClient.convertToType(data['actionTypeId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ActionTypeAdjustmentFactor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ActionTypeAdjustmentFactor</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ActionTypeAdjustmentFactor.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['actionTypeId'] && !(typeof data['actionTypeId'] === 'string' || data['actionTypeId'] instanceof String)) {
            throw new Error("Expected the field `actionTypeId` to be a primitive type in the JSON string but got " + data['actionTypeId']);
        }

        return true;
    }


}

ActionTypeAdjustmentFactor.RequiredProperties = ["adjustmentFactor", "actionTypeId"];

/**
 * The multiplier to apply to source values received for this product events
 * @member {Number} adjustmentFactor
 */
ActionTypeAdjustmentFactor.prototype['adjustmentFactor'] = undefined;

/**
 * A unique system generated identifier for Action Type
 * @member {String} actionTypeId
 */
ActionTypeAdjustmentFactor.prototype['actionTypeId'] = undefined;






export default ActionTypeAdjustmentFactor;

