/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AwardReduced model module.
 * @module model/AwardReduced
 * @version 1.0.17
 */
class AwardReduced {
    /**
     * Constructs a new <code>AwardReduced</code>.
     * 
     * @alias module:model/AwardReduced
     */
    constructor() { 
        
        AwardReduced.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AwardReduced</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AwardReduced} obj Optional instance to populate.
     * @return {module:model/AwardReduced} The populated <code>AwardReduced</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AwardReduced();

            if (data.hasOwnProperty('awardId')) {
                obj['awardId'] = ApiClient.convertToType(data['awardId'], 'String');
            }
            if (data.hasOwnProperty('rewardId')) {
                obj['rewardId'] = ApiClient.convertToType(data['rewardId'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AwardReduced</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AwardReduced</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['awardId'] && !(typeof data['awardId'] === 'string' || data['awardId'] instanceof String)) {
            throw new Error("Expected the field `awardId` to be a primitive type in the JSON string but got " + data['awardId']);
        }
        // ensure the json data is a string
        if (data['rewardId'] && !(typeof data['rewardId'] === 'string' || data['rewardId'] instanceof String)) {
            throw new Error("Expected the field `rewardId` to be a primitive type in the JSON string but got " + data['rewardId']);
        }

        return true;
    }


}



/**
 * A unique identifier of a Award
 * @member {String} awardId
 */
AwardReduced.prototype['awardId'] = undefined;

/**
 * A unique identifier of a Reward
 * @member {String} rewardId
 */
AwardReduced.prototype['rewardId'] = undefined;

/**
 * Numerical value of the award that will be issued
 * @member {Number} value
 */
AwardReduced.prototype['value'] = undefined;






export default AwardReduced;

