/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ConditionalOperator.
* @enum {}
* @readonly
*/
export default class ConditionalOperator {
    
        /**
         * value: "Equals"
         * @const
         */
        "EQUALS" = "Equals";

    
        /**
         * value: "GreaterThan"
         * @const
         */
        "GREATERTHAN" = "GreaterThan";

    
        /**
         * value: "GreaterThanEquals"
         * @const
         */
        "GREATERTHANEQUALS" = "GreaterThanEquals";

    
        /**
         * value: "LessThan"
         * @const
         */
        "LESSTHAN" = "LessThan";

    
        /**
         * value: "LessThanEquals"
         * @const
         */
        "LESSTHANEQUALS" = "LessThanEquals";

    
        /**
         * value: "Between"
         * @const
         */
        "BETWEEN" = "Between";

    

    /**
    * Returns a <code>ConditionalOperator</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ConditionalOperator} The enum <code>ConditionalOperator</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

