/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EntityGraphEdgeType.
* @enum {}
* @readonly
*/
export default class EntityGraphEdgeType {
    
        /**
         * value: "ROOT"
         * @const
         */
        "ROOT" = "ROOT";

    
        /**
         * value: "MUST"
         * @const
         */
        "MUST" = "MUST";

    
        /**
         * value: "SHOULD"
         * @const
         */
        "SHOULD" = "SHOULD";

    
        /**
         * value: "MUST_NOT"
         * @const
         */
        "MUST_NOT" = "MUST_NOT";

    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN" = "UNKNOWN";

    
        /**
         * value: "BROKEN"
         * @const
         */
        "BROKEN" = "BROKEN";

    

    /**
    * Returns a <code>EntityGraphEdgeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EntityGraphEdgeType} The enum <code>EntityGraphEdgeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

