/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstantWinAvailablePlaysRequest model module.
 * @module model/InstantWinAvailablePlaysRequest
 * @version 1.0.19
 */
class InstantWinAvailablePlaysRequest {
    /**
     * Constructs a new <code>InstantWinAvailablePlaysRequest</code>.
     * @alias module:model/InstantWinAvailablePlaysRequest
     * @param instantWinIds {Array.<String>} The game to play.
     */
    constructor(instantWinIds) { 
        
        InstantWinAvailablePlaysRequest.initialize(this, instantWinIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, instantWinIds) { 
        obj['instantWinIds'] = instantWinIds;
    }

    /**
     * Constructs a <code>InstantWinAvailablePlaysRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstantWinAvailablePlaysRequest} obj Optional instance to populate.
     * @return {module:model/InstantWinAvailablePlaysRequest} The populated <code>InstantWinAvailablePlaysRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstantWinAvailablePlaysRequest();

            if (data.hasOwnProperty('instantWinIds')) {
                obj['instantWinIds'] = ApiClient.convertToType(data['instantWinIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The game to play.
 * @member {Array.<String>} instantWinIds
 */
InstantWinAvailablePlaysRequest.prototype['instantWinIds'] = undefined;






export default InstantWinAvailablePlaysRequest;

