/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Award from './Award';
import InstantWinTile from './InstantWinTile';

/**
 * The InstantWinPlayOutcome model module.
 * @module model/InstantWinPlayOutcome
 * @version 1.0.11
 */
class InstantWinPlayOutcome {
    /**
     * Constructs a new <code>InstantWinPlayOutcome</code>.
     * @alias module:model/InstantWinPlayOutcome
     */
    constructor() { 
        
        InstantWinPlayOutcome.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstantWinPlayOutcome</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstantWinPlayOutcome} obj Optional instance to populate.
     * @return {module:model/InstantWinPlayOutcome} The populated <code>InstantWinPlayOutcome</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstantWinPlayOutcome();

            if (data.hasOwnProperty('awards')) {
                obj['awards'] = ApiClient.convertToType(data['awards'], [Award]);
            }
            if (data.hasOwnProperty('tiles')) {
                obj['tiles'] = ApiClient.convertToType(data['tiles'], [InstantWinTile]);
            }
        }
        return obj;
    }


}

/**
 * The awards that the member unlocked
 * @member {Array.<module:model/Award>} awards
 */
InstantWinPlayOutcome.prototype['awards'] = undefined;

/**
 * The tiles uncovered during the game session, for the wheel of fortune this will be the slice the player landed on for a scratch card it would be the revealed tiles
 * @member {Array.<module:model/InstantWinTile>} tiles
 */
InstantWinPlayOutcome.prototype['tiles'] = undefined;






export default InstantWinPlayOutcome;

