/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstantWinFilter from './InstantWinFilter';

/**
 * The InstantWinRequest model module.
 * @module model/InstantWinRequest
 * @version 1.0.16
 */
class InstantWinRequest {
    /**
     * Constructs a new <code>InstantWinRequest</code>.
     * @alias module:model/InstantWinRequest
     */
    constructor() { 
        
        InstantWinRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstantWinRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstantWinRequest} obj Optional instance to populate.
     * @return {module:model/InstantWinRequest} The populated <code>InstantWinRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstantWinRequest();

            if (data.hasOwnProperty('instantWinFilter')) {
                obj['instantWinFilter'] = InstantWinFilter.constructFromObject(data['instantWinFilter']);
            }
            if (data.hasOwnProperty('languageKey')) {
                obj['languageKey'] = ApiClient.convertToType(data['languageKey'], 'String');
            }
            if (data.hasOwnProperty('currencyKey')) {
                obj['currencyKey'] = ApiClient.convertToType(data['currencyKey'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InstantWinFilter} instantWinFilter
 */
InstantWinRequest.prototype['instantWinFilter'] = undefined;

/**
 * The language codes can be found in the settings/transalations section of the back office
 * @member {String} languageKey
 */
InstantWinRequest.prototype['languageKey'] = undefined;

/**
 * The UoM currency key to normalise the value to for presentation. Example; If the reward is in EUR and this value is set to USD then the value will be multiplied by 1.09387699997429
 * @member {String} currencyKey
 */
InstantWinRequest.prototype['currencyKey'] = undefined;






export default InstantWinRequest;

