/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstantWinTile from './InstantWinTile';

/**
 * The InstantWinAllOf model module.
 * @module model/InstantWinAllOf
 * @version 1.0.16
 */
class InstantWinAllOf {
    /**
     * Constructs a new <code>InstantWinAllOf</code>.
     * @alias module:model/InstantWinAllOf
     * @param instantWinType {Number} 
     * @param tiles {Array.<module:model/InstantWinTile>} 
     */
    constructor(instantWinType, tiles) { 
        
        InstantWinAllOf.initialize(this, instantWinType, tiles);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, instantWinType, tiles) { 
        obj['instantWinType'] = instantWinType;
        obj['tiles'] = tiles;
    }

    /**
     * Constructs a <code>InstantWinAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstantWinAllOf} obj Optional instance to populate.
     * @return {module:model/InstantWinAllOf} The populated <code>InstantWinAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstantWinAllOf();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('termsAndConditions')) {
                obj['termsAndConditions'] = ApiClient.convertToType(data['termsAndConditions'], 'String');
            }
            if (data.hasOwnProperty('constraints')) {
                obj['constraints'] = ApiClient.convertToType(data['constraints'], ['String']);
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('instantWinType')) {
                obj['instantWinType'] = ApiClient.convertToType(data['instantWinType'], 'Number');
            }
            if (data.hasOwnProperty('iconLink')) {
                obj['iconLink'] = ApiClient.convertToType(data['iconLink'], 'String');
            }
            if (data.hasOwnProperty('bannerLink')) {
                obj['bannerLink'] = ApiClient.convertToType(data['bannerLink'], 'String');
            }
            if (data.hasOwnProperty('bannerLowResolutionLink')) {
                obj['bannerLowResolutionLink'] = ApiClient.convertToType(data['bannerLowResolutionLink'], 'String');
            }
            if (data.hasOwnProperty('bannerHighResolutionLink')) {
                obj['bannerHighResolutionLink'] = ApiClient.convertToType(data['bannerHighResolutionLink'], 'String');
            }
            if (data.hasOwnProperty('tiles')) {
                obj['tiles'] = ApiClient.convertToType(data['tiles'], [InstantWinTile]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
InstantWinAllOf.prototype['name'] = undefined;

/**
 * @member {String} description
 */
InstantWinAllOf.prototype['description'] = undefined;

/**
 * @member {String} termsAndConditions
 */
InstantWinAllOf.prototype['termsAndConditions'] = undefined;

/**
 * Additional constraints, if set means true [optinRequiredForEntrants, hasRules, hasRewards]
 * @member {Array.<String>} constraints
 */
InstantWinAllOf.prototype['constraints'] = undefined;

/**
 * @member {Number} statusCode
 */
InstantWinAllOf.prototype['statusCode'] = undefined;

/**
 * @member {Number} instantWinType
 */
InstantWinAllOf.prototype['instantWinType'] = undefined;

/**
 * Attachement id for the corresponding icon image.
 * @member {String} iconLink
 */
InstantWinAllOf.prototype['iconLink'] = undefined;

/**
 * Link to the banner
 * @member {String} bannerLink
 */
InstantWinAllOf.prototype['bannerLink'] = undefined;

/**
 * Link to the bannerLowResolution
 * @member {String} bannerLowResolutionLink
 */
InstantWinAllOf.prototype['bannerLowResolutionLink'] = undefined;

/**
 * Link to the bannerHighResolution
 * @member {String} bannerHighResolutionLink
 */
InstantWinAllOf.prototype['bannerHighResolutionLink'] = undefined;

/**
 * @member {Array.<module:model/InstantWinTile>} tiles
 */
InstantWinAllOf.prototype['tiles'] = undefined;






export default InstantWinAllOf;

