/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SimilarToProductRequest model module.
 * @module model/SimilarToProductRequest
 * @version 1.0.10
 */
class SimilarToProductRequest {
    /**
     * Constructs a new <code>SimilarToProductRequest</code>.
     * @alias module:model/SimilarToProductRequest
     */
    constructor() { 
        
        SimilarToProductRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SimilarToProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SimilarToProductRequest} obj Optional instance to populate.
     * @return {module:model/SimilarToProductRequest} The populated <code>SimilarToProductRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimilarToProductRequest();

            if (data.hasOwnProperty('skip')) {
                obj['skip'] = ApiClient.convertToType(data['skip'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} skip
 */
SimilarToProductRequest.prototype['skip'] = undefined;

/**
 * @member {Number} limit
 */
SimilarToProductRequest.prototype['limit'] = undefined;

/**
 * @member {String} id
 */
SimilarToProductRequest.prototype['id'] = undefined;






export default SimilarToProductRequest;

