/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnsubscribeRequest model module.
 * @module model/UnsubscribeRequest
 * @version 1.0.17
 */
class UnsubscribeRequest {
    /**
     * Constructs a new <code>UnsubscribeRequest</code>.
     * 
     * @alias module:model/UnsubscribeRequest
     * @param sunscriptionId {String} 
     */
    constructor(sunscriptionId) { 
        
        UnsubscribeRequest.initialize(this, sunscriptionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sunscriptionId) { 
        obj['sunscriptionId'] = sunscriptionId;
    }

    /**
     * Constructs a <code>UnsubscribeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UnsubscribeRequest} obj Optional instance to populate.
     * @return {module:model/UnsubscribeRequest} The populated <code>UnsubscribeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnsubscribeRequest();

            if (data.hasOwnProperty('sunscriptionId')) {
                obj['sunscriptionId'] = ApiClient.convertToType(data['sunscriptionId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UnsubscribeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UnsubscribeRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UnsubscribeRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['sunscriptionId'] && !(typeof data['sunscriptionId'] === 'string' || data['sunscriptionId'] instanceof String)) {
            throw new Error("Expected the field `sunscriptionId` to be a primitive type in the JSON string but got " + data['sunscriptionId']);
        }

        return true;
    }


}

UnsubscribeRequest.RequiredProperties = ["sunscriptionId"];

/**
 * 
 * @member {String} sunscriptionId
 */
UnsubscribeRequest.prototype['sunscriptionId'] = undefined;






export default UnsubscribeRequest;

