/**
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import superagent from "superagent";
import querystring from "querystring";

/**
* @module ApiClient
* @version 0.0.1
*/

/**
* Manages low level client-server communications, parameter marshalling, etc. There should not be any need for an
* application to use this class directly - the *Api and model classes provide the public API for the service. The
* contents of this file should be regarded as internal but are documented for completeness.
* @alias module:ApiClient
* @class
*/
class ApiClientStomp {
    /**
     * The base URL against which to resolve every API call's (relative) path.
     * Overrides the default value set in spec file if present
     * @param {String} basePath
     */
    constructor(basePath = 'wss://member-api.ziqni.com/ws') {
        /**
         * The base URL against which to resolve every API call's (relative) path.
         * @type {String}
         * @default https://member-api.ziqni.com
         */
        this.basePath = basePath.replace(/\/+$/, '');

        /**
         * The authentication methods to be included for all API calls.
         * @type {Array.<String>}
         */
        this.authentications = {
            'OAuth2': {type: 'oauth2'}
        }

        /**
         * The default HTTP headers to be included for all API calls.
         * @type {Array.<String>}
         * @default {}
         */
        this.defaultHeaders = {
            'User-Agent': 'OpenAPI-Generator/0.0.1/Javascript'
        };

        /**
         * The default HTTP timeout for all API calls.
         * @type {Number}
         * @default 60000
         */
        this.timeout = 60000;

        /**
         * If set to false an additional timestamp parameter is added to all API GET calls to
         * prevent browser caching
         * @type {Boolean}
         * @default true
         */
        this.cache = true;

        /**
         * If set to true, the client will save the cookies from each server
         * response, and return them in the next request.
         * @default false
         */
        this.enableCookies = false;

        /*
         * Used to save and return cookies in a node.js (non-browser) setting,
         * if this.enableCookies is set to true.
         */
        if (typeof window === 'undefined') {
          this.agent = new superagent.agent();
        }

        /*
         * Allow user to override superagent agent
         */
         this.requestAgent = null;

        /*
         * Allow user to add superagent plugins
         */
        this.plugins = null;

        this.rpcCallBacks = new Map();

    }

    /**
    * Returns a string representation for an actual parameter.
    * @param param The actual parameter.
    * @returns {String} The string representation of <code>param</code>.
    */
    connect(param) {
        const client = new StompJs.Client({
            brokerURL: 'wss://member-api.ziqni.com/ws',
            connectHeaders: {
                login: 'Bearer',
                passcode: 'eyJhbGciOiJIUzI1NiJ9.eyJhcGlfa2V5X2lkIjoicXhtcXFZRUJUZVV0U0VzNEVJLWgiLCJtZW1iZXJfcmVmZXJlbmNlX2lkIjoiMTAwMDI1NDE5IiwiYWNjb3VudF9pZCI6IkY3bThkSHdCc3ctT0gzTUVvVzIzIiwic3BhY2VfbmFtZSI6ImZpcnN0LXNwYWNlIiwibmFtZSI6Im5hbWUxIiwibWVtYmVyX3R5cGUiOiJJbmRpdmlkdWFsIiwibWVtYmVyX2lkIjoiX01XRmtJRUJaNUNYN2RXbnFhR0kiLCJyZXNvdXJjZV9hY2Nlc3MiOnsiemlxbmktZ2FwaSI6eyJyb2xlcyI6WyJQdWJsaWMiLCJNZW1iZXIiLCJWaWV3QWNoaWV2ZW1lbnRzIiwiVmlld0F3YXJkcyIsIkNsYWltQXdhcmRzIiwiVmlld0NvbXBldGl0aW9ucyIsIlZpZXdDb250ZXN0cyIsIlZpZXdGaWxlcyIsIlZpZXdNZW1iZXJzIiwiTWVtYmVyc09wdGluIiwiVmlld01lc3NhZ2VzIiwiQ29ubmVjdFByb3h5IiwiVmlld1Jld2FyZHMiLCJWaWV3UnVsZXMiXX19LCJzdWIiOiJfTVdGa0lFQlo1Q1g3ZFducWFHSSIsImp0aSI6ImEyMmM3N2RmLWMzMTEtNGNiYS1iOWQ2LTBjNTU5YzE4Mjc2ZiIsImlhdCI6MTY1NzAwNjA5MywiZXhwIjoyMzI1NzAwNjA5M30.FB-c9I2im-dQWZ-ggUmOELj259rUfgAWJDWccXmZEiQ', // 'JWT token you get from https://api.ziqni.com/swagger-ui/#/member-token/createMemberToken',
            },
            debug: function (str) {
                console.log(str);
            },
            reconnectDelay: 5000,
            heartbeatIncoming: 4000,
            heartbeatOutgoing: 4000,
        });

        // Fallback code
        if (typeof WebSocket !== 'function') {
            // For SockJS you need to set a factory that creates a new SockJS instance
            // to be used for each (re)connect
            client.webSocketFactory = function () {
                // Note that the URL is different from the WebSocket URL
                return new SockJS('https://api.ziqni.com/ws/info');
            };
        }

        client.onConnect = function (frame) {
            // Do something, all subscribes must be done is this callback
            // This is needed because this will be executed after a (re)connect
        };

        client.onStompError = function (frame) {
            // Will be invoked in case of error encountered at Broker
            // Bad login/passcode typically will cause an error
            // Complaint brokers will set `message` header with a brief message. Body may contain details.
            // Compliant brokers will terminate the connection after any error
            console.log('Broker reported error: ' + frame.headers['message']);
            console.log('Additional details: ' + frame.body);
        };

        client.activate();

        let rpcCallbackSubscription = client.subscribe("/user/queue/rpc-results", handleRpcCallback);
        let sysCallbackSubscription = client.subscribe("/user/queue/callbacks", handleSysCallback);

        // We need to subscribe to:
        // topic ==> /user/queue/callbacks
        // and
        // topic ==> /user/queue/rpc-results

        // We send messages to /gapi/getMember
        // We always prefix with /gapi/<Operation-ID> like getMessages, getRewards etc will be /gapi/getMessages /gapi/getRewards
        //
        //  messageHeaders.setMessageId(nextSeq) ==> nextSeq is added to the callback so we can correlate the response to the request
        //
        // message = { data: MemberRequest }
        //
        //
        // client.send('/gapi/getMember', messageHeaders, JSON.stringify(message));
    }

    uuidv4() {
        return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
            (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
        );
    }

    handleRpcCallback = function(message) {
        // called when the client receives a STOMP message from the server
        if (message.body) {
            // Get the messageId then
            //this.rpcCallBacks.get(messageId)(message.body)
            alert("got message with body " + message.body)
        } else {
            alert("got empty message");
        }
    };

    handleSysCallback = function(message) {
        // called when the client receives a STOMP message from the server
        if (message.body) {
            alert("got message with body " + message.body)
        } else {
            alert("got empty message");
        }
    };

    sendRpc(to, message, callback){
        let messageId = apiClientStomp.uuidv4();
        let messageHeaders = messageHeaders.setMessageId(messageId);
        let messageContainer = { body: message };
        apiClientStomp.send('/gapi/getMember', messageHeaders, JSON.stringify(messageContainer));
        this.rpcCallBacks.set(messageId, callback)
    }
}



/**
* The default API  Stomp client implementation.
* @type {module:ApiClientStomp}
*/
ApiClientStomp.instance = new ApiClientStomp();
export default ApiClientStomp;
