/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for CompetitionResponse
 */
public class CompetitionResponseTest {
    private final CompetitionResponse model = new CompetitionResponse();

    /**
     * Model tests for CompetitionResponse
     */
    @Test
    public void testCompetitionResponse() {
        // TODO: test CompetitionResponse
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
