/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for CompetitionRequest
 */
public class CompetitionRequestTest {
    private final CompetitionRequest model = new CompetitionRequest();

    /**
     * Model tests for CompetitionRequest
     */
    @Test
    public void testCompetitionRequest() {
        // TODO: test CompetitionRequest
    }

    /**
     * Test the property 'memberRefId'
     */
    @Test
    public void memberRefIdTest() {
        // TODO: test memberRefId
    }

    /**
     * Test the property 'competitionFilter'
     */
    @Test
    public void competitionFilterTest() {
        // TODO: test competitionFilter
    }

}
