/*
 * Ziqni Member Cloud API
 * This is the Member cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for ContestFilter
 */
public class ContestFilterTest {
    private final ContestFilter model = new ContestFilter();

    /**
     * Model tests for ContestFilter
     */
    @Test
    public void testContestFilter() {
        // TODO: test ContestFilter
    }

    /**
     * Test the property 'productIds'
     */
    @Test
    public void productIdsTest() {
        // TODO: test productIds
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    public void sortByTest() {
        // TODO: test sortBy
    }

    /**
     * Test the property 'competitionIds'
     */
    @Test
    public void competitionIdsTest() {
        // TODO: test competitionIds
    }

    /**
     * Test the property 'skip'
     */
    @Test
    public void skipTest() {
        // TODO: test skip
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

}
