/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for MessageRequest
 */
public class MessageRequestTest {
    private final MessageRequest model = new MessageRequest();

    /**
     * Model tests for MessageRequest
     */
    @Test
    public void testMessageRequest() {
        // TODO: test MessageRequest
    }

    /**
     * Test the property 'memberRefId'
     */
    @Test
    public void memberRefIdTest() {
        // TODO: test memberRefId
    }

}
