/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for RankingStrategy
 */
public class RankingStrategyTest {
    private final RankingStrategy model = new RankingStrategy();

    /**
     * Model tests for RankingStrategy
     */
    @Test
    public void testRankingStrategy() {
        // TODO: test RankingStrategy
    }

    /**
     * Test the property 'constraints'
     */
    @Test
    public void constraintsTest() {
        // TODO: test constraints
    }

}
