/*
 * Ziqni Member Cloud API
 * This is the Member cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for RewardReduced
 */
public class RewardReducedTest {
    private final RewardReduced model = new RewardReduced();

    /**
     * Model tests for RewardReduced
     */
    @Test
    public void testRewardReduced() {
        // TODO: test RewardReduced
    }

    /**
     * Test the property 'rewardRank'
     */
    @Test
    public void rewardRankTest() {
        // TODO: test rewardRank
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rewardValue'
     */
    @Test
    public void rewardValueTest() {
        // TODO: test rewardValue
    }

    /**
     * Test the property 'rewardType'
     */
    @Test
    public void rewardTypeTest() {
        // TODO: test rewardType
    }

    /**
     * Test the property 'rewardTypeId'
     */
    @Test
    public void rewardTypeIdTest() {
        // TODO: test rewardTypeId
    }

}
