/*
 * Ziqni Member Cloud API
 * This is the Member cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for RewardTypeReduced
 */
public class RewardTypeReducedTest {
    private final RewardTypeReduced model = new RewardTypeReduced();

    /**
     * Model tests for RewardTypeReduced
     */
    @Test
    public void testRewardTypeReduced() {
        // TODO: test RewardTypeReduced
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

}
