/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for RuleExpression
 */
public class RuleExpressionTest {
    private final RuleExpression model = new RuleExpression();

    /**
     * Model tests for RuleExpression
     */
    @Test
    public void testRuleExpression() {
        // TODO: test RuleExpression
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'mustMatchAll'
     */
    @Test
    public void mustMatchAllTest() {
        // TODO: test mustMatchAll
    }

    /**
     * Test the property 'mustEvaluateTo'
     */
    @Test
    public void mustEvaluateToTest() {
        // TODO: test mustEvaluateTo
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'operand'
     */
    @Test
    public void operandTest() {
        // TODO: test operand
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'rules'
     */
    @Test
    public void rulesTest() {
        // TODO: test rules
    }

    /**
     * Test the property 'then'
     */
    @Test
    public void thenTest() {
        // TODO: test then
    }

    /**
     * Test the property 'lineNumber'
     */
    @Test
    public void lineNumberTest() {
        // TODO: test lineNumber
    }

}
