/*
 * Ziqni Member Cloud API
 * This is the Member cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.model;

import org.junit.jupiter.api.*;

/**
 * Model tests for ScoringStrategy
 */
public class ScoringStrategyTest {
    private final ScoringStrategy model = new ScoringStrategy();

    /**
     * Model tests for ScoringStrategy
     */
    @Test
    public void testScoringStrategy() {
        // TODO: test ScoringStrategy
    }

    /**
     * Test the property 'limitUpdatesTo'
     */
    @Test
    public void limitUpdatesToTest() {
        // TODO: test limitUpdatesTo
    }

    /**
     * Test the property 'sumBestXOf'
     */
    @Test
    public void sumBestXOfTest() {
        // TODO: test sumBestXOf
    }

    /**
     * Test the property 'lastUpdateTimeStamp'
     */
    @Test
    public void lastUpdateTimeStampTest() {
        // TODO: test lastUpdateTimeStamp
    }

    /**
     * Test the property 'recordTimeWhenSumReaches'
     */
    @Test
    public void recordTimeWhenSumReachesTest() {
        // TODO: test recordTimeWhenSumReaches
    }

}
