openapi: 3.0.2
info:
    title: ZIQNI Member API
    version: 1.0.1
    description: >-
        The ZIQNI Member-API is the primary resource used to build services and widgets for your members
        [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the
        system is decribed using OpenApi schema for convenience.
servers:
    -
        url: 'https://member-api.ziqni.com'
        description: Live
paths:
    /member-info:
        summary: Member information
        description: The endpoint provides information about the member.
        post:
            tags:
                - members
            security:
                -
                    OAuth2:
                        - ViewMembers
            operationId: getMember
            summary: Get member information by member reference id
            description: Returns member information for the provided member reference id
            x-ws-only: true
    /rewards:
        summary: Reward operations
        description: This endpoint is used to perform reward operations.
        post:
            tags:
                - rewards
            security:
                -
                    OAuth2:
                        - ViewRewards
            operationId: getRewards
            summary: Get rewards
            description: This operation support retrieval of rewards for one or many entitites.
            x-ws-only: true
    /rules:
        summary: Rules operations
        description: This endpoint is used to perform rules operations.
        post:
            tags:
                - rules
            security:
                -
                    OAuth2:
                        - ViewRules
            operationId: getRules
            summary: Get rules
            description: This operation support retrieval of rules for one or many entities.
            x-ws-only: true
    /achievements:
        summary: Member achievements operation
        description: This endpoint supports member's achievements operation.
        post:
            tags:
                - achievements
            security:
                -
                    OAuth2:
                        - ViewAchievements
            operationId: getAchievements
            summary: Get achievements by member reference id
            description: Returns a list of achievements for the provided member ref id and applied filters.
            x-ws-only: true
    /awards:
        summary: Award operations
        description: This endpoint is used to perform award operations.
        post:
            tags:
                - awards
            security:
                -
                    OAuth2:
                        - ViewAwards
            operationId: getAwards
            summary: Get awards.
            description: This operation supports retrieval of awards for one or many entities.
            x-ws-only: true
    /awards-claim:
        summary: Award operations
        description: This endpoint is used to perform award operations.
        post:
            tags:
                - awards
            security:
                -
                    OAuth2:
                        - ClaimAwards
            operationId: claimAwards
            summary: Claim awards.
            description: This operation enables a member to claim awards.
            x-ws-only: true
    /competitions:
        summary: Member competitions operation
        description: This endpoint supports member's competitions operation.
        post:
            tags:
                - competitions
            security:
                -
                    OAuth2:
                        - ViewCompetitions
            operationId: getCompetitions
            summary: Get competitions by member reference id
            description: Returns a list of competitions for the provided member ref id and applied filters.
            x-ws-only: true
    /contests:
        summary: Member contests operation
        description: This endpoint supports member's contests operation.
        post:
            tags:
                - contests
            security:
                -
                    OAuth2:
                        - ViewContests
            operationId: getContests
            summary: Get contests by member reference Id
            description: Returns a list of contests for the provided member ref id and applied filters.
            x-ws-only: true
    /files:
        summary: Files operations
        description: This endpoint is used to perform files operations.
        post:
            tags:
                - files
            operationId: getFiles
            summary: Get files.
            description: This operation supports retrieval of file objects for one or many entities.
            x-ws-only: true
    /manage-optin:
        summary: Member optin operation
        description: This endpoint supports member's optin operation.
        post:
            tags:
                - opt-in
            security:
                -
                    OAuth2:
                        - ViewMembers
            operationId: manageOptin
            summary: Get member optin information
            description: Returns a list of member optin information
            x-ws-only: true
    /leaderboard:
        post:
            tags:
                - leaderboard
            operationId: subscribeToLeaderboard
    /messages:
        summary: Member messages operation
        description: This endpoint supports member's messages operation.
        post:
            tags:
                - messages
            security:
                -
                    OAuth2:
                        - ViewMessages
            operationId: getMessages
            summary: Get messages by member reference id
            description: Returns a list of messages for the provided member ref id and applied filters.
            x-ws-only: true
    /optin-states:
        summary: Member optin operation
        description: This endpoint supports member's optin operation.
        post:
            tags:
                - opt-in
            security:
                -
                    OAuth2:
                        - ViewMembers
            operationId: optInStates
            summary: Get member optin status information
            description: Returns a list of member optin status information
            x-ws-only: true
    /heartbeat:
        post:
            tags:
                - heartbeat
            operationId: heartbeat
    /callbacks:
        description: For websockets use this queue "/queue/callbacks" to receive push messages.
        get:
            tags:
                - callbacks
            operationId: listCallbacks
            summary: Describe the system callbacks and there constraints
            description: subscribes a client to receive out-of-band data
    /graphs:
        summary: Structures the connections data as a graph.
        description: >-
            The ZIQNI graph data structure consists of a finite (and possibly mutable) set of vertices (also
            called nodes or points), together with a set of ordered pairs for a directed graph. These pairs
            are known as edges (also called links or lines), and for a directed graph are also known as edges
            but also sometimes arrows or arcs whicj are joined using the dependant on must or should within
            achievements.
        post:
            tags:
                - graphs
            security:
                -
                    OAuth2:
                        - ViewMissions
            operationId: getGraph
            summary: Get achievements by member reference id
            description: Returns a list of graphs based on the entity type.
            x-ws-only: true
components:
    securitySchemes:
        OAuth2:
            flows:
                authorizationCode:
                    authorizationUrl: 'https://iam.ziqni.io/oauth/authorize'
                    tokenUrl: 'https://iam.ziqni.io/oauth/token'
                    scopes:
                        ViewContests: Grants read access
                        ViewCompetitions: Grants read access
                        ViewAchievements: Grants read access
                        ViewRewards: Grants read access
                        ViewMessages: Grants read access
                        ViewAwards: Grants read access
                        ViewRules: Grants read access
                        ViewMembers: Grants read access
            type: oauth2
tags:
    -
        name: competitions
        description: Perform POST operations on Competitions
    -
        name: achievements
        description: Perform POST operations on Achievements
    -
        name: contests
        description: Perform POST operations on Contests
    -
        name: messages
        description: Perform POST operations on Messages
    -
        name: rewards
        description: Perform POST operations on Rewards
    -
        name: rules
        description: Perform POST operations on Rules
    -
        name: proxy
        description: Perform POST operations on Proxy
    -
        name: members
        description: Perform POST operations on Members
    -
        name: awards
        description: Perform POST operations on Awards
    -
        name: files
        description: Perform POST operations on Files
