openapi: 3.0.2
info:
  title: Ziqni Gamification Cloud API
  version: 1.0.0
  description: This is the gamification cloud for Ziqni
servers:
  -
    url: 'https://gamification-api.ziqni.com'
    description: Live
paths:
  /gc/achievements:
    summary: Member achievements operation
    description: This endpoint supports member's achievements operation.
    post:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ViewAchievements
      operationId: getAchievements
      summary: Get achievements by member reference id
      description: Returns a list of achievements for the provided member ref id and applied filters.
  /gc/competitions:
    summary: Member competitions operation
    description: This endpoint supports member's competitions operation.
    post:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: getCompetitions
      summary: Get competitions by member reference id
      description: Returns a list of competitions for the provided member ref id and applied filters.
  /gc/rewards:
    summary: Reward operations
    description: This endpoint is used to perform reward operations.
    post:
      tags:
        - rewards
      security:
        -
          OAuth2:
            - ViewRewards
      operationId: getRewards
      summary: Get rewards
      description: This operation support retrieval of rewards for one or many entitites.
  /gc/rules:
    summary: Rules operations
    description: This endpoint is used to perform rules operations.
    post:
      tags:
        - rules
      security:
        -
          OAuth2:
            - ViewRules
      operationId: getRules
      summary: Get rules
      description: This operation support retrieval of rules for one or many entities.
  /gc/messages:
    summary: Member messages operation
    description: This endpoint supports member's messages operation.
    post:
      tags:
        - messages
      security:
        -
          OAuth2:
            - ViewMessages
      operationId: getMessages
      summary: Get messages by member reference id
      description: Returns a list of messages for the provided member ref id and applied filters.
  /gc/proxy:
    summary: Proxy operation
    description: Support proxy operations
    post:
      tags:
        - proxy
      operationId: proxy
      summary: Proxy
      description: Perform proxy operations.
  /gc/member-info:
    summary: Member information
    description: The endpoint provides information about the member.
    post:
      tags:
        - members
      security:
        -
          OAuth2:
            - ViewMembers
      operationId: getMember
      summary: Get member information by member reference id
      description: Returns member information for the provided member reference id
  /gc/member-session:
    summary: Member session
    description: This endpoint provides member's active session information.
    post:
      tags:
        - members
      security:
        -
          OAuth2:
            - ViewMembers
      operationId: getMemberSession
      summary: Get member session by member reference id
      description: Returns member's active session information.
  /gc/awards:
    summary: Award operations
    description: This endpoint is used to perform award operations.
    post:
      tags:
        - awards
      security:
        -
          OAuth2:
            - ViewAwards
      operationId: getAwards
      summary: Get awards.
      description: This operation supports retrieval of awards for one or many entities.
  /gc/member-manage-optin:
    summary: Member optin operation
    description: This endpoint supports member's optin operation.
    post:
      tags:
        - members
      security:
        -
          OAuth2:
            - ViewMembers
      operationId: getMemberOptinInfo
      summary: Get member optin information
      description: Returns a list of member optin information
  /gc/files:
    summary: Files operations
    description: This endpoint is used to perform files operations.
    post:
      tags:
        - files
      operationId: getFiles
      summary: Get files.
      description: This operation supports retrieval of file objects for one or many entities.
  /gc/awards-claim:
    summary: Award operations
    description: This endpoint is used to perform award operations.
    post:
      tags:
        - awards
      security:
        -
          OAuth2:
            - ClaimAwards
      operationId: claimAwards
      summary: Claim awards.
      description: This operation enables a member to claim awards.
  /gc/contests:
    summary: Member contests operation
    description: This endpoint supports member's contests operation.
    post:
      tags:
        - contests
      security:
        -
          OAuth2:
            - ViewContests
      operationId: getContests
      summary: Get contests by member reference Id
      description: Returns a list of contests for the provided member ref id and applied filters.
  /gc/get-token:
    description: >-
      The services returns a JWT token used to authorize requests to the other service end points. Use
      this JWT as an auth header parameter for future requests: 
      
      --header 'Authorization: Bearer <jwt-token-from-api>'
    post:
      tags:
        - token
      operationId: getToken
      description: Get Jwt Token
      x-ws-exclude: true
components:
  securitySchemes:
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: 'https://iam.ziqni.io/oauth/authorize'
          tokenUrl: 'https://iam.ziqni.io/oauth/token'
          scopes:
            ViewContests: Grants read access
            ViewCompetitions: Grants read access
            ViewAchievements: Grants read access
            ViewRewards: Grants read access
            ViewMessages: Grants read access
            ViewAwards: Grants read access
            ViewRules: Grants read access
            ViewMembers: Grants read access
      type: oauth2
tags:
  -
    name: competitions
    description: Perform POST operations on Competitions
  -
    name: token
    description: Perform POST operations on Token
  -
    name: achievements
    description: Perform POST operations on Achievements
  -
    name: contests
    description: Perform POST operations on Contests
  -
    name: messages
    description: Perform POST operations on Messages
  -
    name: rewards
    description: Perform POST operations on Rewards
  -
    name: rules
    description: Perform POST operations on Rules
  -
    name: proxy
    description: Perform POST operations on Proxy
  -
    name: members
    description: Perform POST operations on Members
  -
    name: awards
    description: Perform POST operations on Awards
  -
    name: files
    description: Perform POST operations on Files
