/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClientStomp', 'model/EntityChangeSubscriptionRequest', 'model/EntityChangeSubscriptionResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClientStomp'), require('../model/EntityChangeSubscriptionRequest'), require('../model/EntityChangeSubscriptionResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.ZiqniMemberApi) {
      root.ZiqniMemberApi = {};
    }
    root.ZiqniMemberApi.EntityChangesApi = factory(root.ZiqniMemberApi.ApiClientStomp, root.ZiqniMemberApi.EntityChangeSubscriptionRequest, root.ZiqniMemberApi.EntityChangeSubscriptionResponse);
  }
}(this, function(ApiClientStomp, EntityChangeSubscriptionRequest, EntityChangeSubscriptionResponse) {
  'use strict';

  /**
   * EntityChanges service.
   * @module api/EntityChangesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new EntityChangesApi. 
   * @alias module:api/EntityChangesApi
   * @class
   * @param {module:ApiClientStomp} [apiClientStomp] Optional API client implementation to use,
   * default to {@link module:ApiClientStomp#instance} if unspecified.
   */
  var exports = function(apiClientStomp) {
    this.apiClientStomp = apiClientStomp || ApiClientStomp.instance;


    /**
     * Callback function to receive the result of the subscribeToEntityChanges operation.
     * @callback module:api/EntityChangesApi~subscribeToEntityChangesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EntityChangeSubscriptionResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * subscribes a client to receive out-of-band data
     * @param {module:model/EntityChangeSubscriptionRequest} entityChangeSubscriptionRequest subscription payload
     * @param {module:api/EntityChangesApi~subscribeToEntityChangesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EntityChangeSubscriptionResponse}
     */
    this.subscribeToEntityChanges = function(entityChangeSubscriptionRequest, callback) {
      var postBody = entityChangeSubscriptionRequest;
      // verify the required parameter 'entityChangeSubscriptionRequest' is set
      if (entityChangeSubscriptionRequest === undefined || entityChangeSubscriptionRequest === null) {
        throw new Error("Missing the required parameter 'entityChangeSubscriptionRequest' when calling subscribeToEntityChanges");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };
      var destination = '/gapi/subscribeToEntityChanges';

      var returnType = EntityChangeSubscriptionResponse;
      return this.apiClientStomp.sendRpc(destination, callback, pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody, returnType);
    }
  };

  return exports;
}));
