/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClientStomp', 'model/EntityRequest', 'model/RuleResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClientStomp'), require('../model/EntityRequest'), require('../model/RuleResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.ZiqniMemberApi) {
      root.ZiqniMemberApi = {};
    }
    root.ZiqniMemberApi.RulesApi = factory(root.ZiqniMemberApi.ApiClientStomp, root.ZiqniMemberApi.EntityRequest, root.ZiqniMemberApi.RuleResponse);
  }
}(this, function(ApiClientStomp, EntityRequest, RuleResponse) {
  'use strict';

  /**
   * Rules service.
   * @module api/RulesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new RulesApi. 
   * @alias module:api/RulesApi
   * @class
   * @param {module:ApiClientStomp} [apiClientStomp] Optional API client implementation to use,
   * default to {@link module:ApiClientStomp#instance} if unspecified.
   */
  var exports = function(apiClientStomp) {
    this.apiClientStomp = apiClientStomp || ApiClientStomp.instance;


    /**
     * Callback function to receive the result of the getRules operation.
     * @callback module:api/RulesApi~getRulesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RuleResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get rules
     * This operation support retrieval of rules for one or many entities.
     * @param {module:model/EntityRequest} entityRequest 
     * @param {module:api/RulesApi~getRulesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RuleResponse}
     */
    this.getRules = function(entityRequest, callback) {
      var postBody = entityRequest;
      // verify the required parameter 'entityRequest' is set
      if (entityRequest === undefined || entityRequest === null) {
        throw new Error("Missing the required parameter 'entityRequest' when calling getRules");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };
      var destination = '/gapi/getRules';

      var returnType = RuleResponse;
      return this.apiClientStomp.sendRpc(destination, callback, pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody, returnType);
    }
  };

  return exports;
}));
