/**
 * ZIQNI Member API
 * The ZIQNI Member-API is the primary resource used to build services and widgets for your members [customers, players, patients, etc]. The service is Stomp websokets with SOCK.js even though the system is decribed using OpenApi schema for convenience.
 *
 * The version of the OpenAPI document: 1.0.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ModelCountRequest from '../model/ModelCountRequest';
import ModelCountResponse from '../model/ModelCountResponse';

/**
* Stats service.
* @module api/StatsApi
* @version 1.0.14
*/
export default class StatsApi {

    /**
    * Constructs a new StatsApi. 
    * @alias module:api/StatsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getActiveEntitiesCount operation.
     * @callback module:api/StatsApi~getActiveEntitiesCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelCountResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get competitions and/or achievements count by product id or reference id
     * Returns the count of active competitions and/or achievements by product id or reference id
     * @param {module:model/ModelCountRequest} modelCountRequest 
     * @param {module:api/StatsApi~getActiveEntitiesCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelCountResponse}
     */
    getActiveEntitiesCount(modelCountRequest, callback) {
      let postBody = modelCountRequest;
      // verify the required parameter 'modelCountRequest' is set
      if (modelCountRequest === undefined || modelCountRequest === null) {
        throw new Error("Missing the required parameter 'modelCountRequest' when calling getActiveEntitiesCount");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ModelCountResponse;
      return this.apiClient.callApi(
        '/actives-by-entity', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
