/*
 * Ziqni Gamification Cloud API
 * This is the gamification cloud for Ziqni
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.member.sdk.api;

import com.ziqni.member.sdk.ApiClientFactoryWs;
import com.ziqni.member.sdk.ApiException;
import com.ziqni.member.sdk.model.ProxyRequest;
import com.ziqni.member.sdk.model.ProxyResponse;
import org.junit.jupiter.api.*;

import java.util.concurrent.CompletableFuture;

/**
 * API tests for ProxyApi
 */

public class ProxyApiTest {

    private final ProxyApiWs api;

    public ProxyApiTest() {
        this.api = ApiClientFactoryWs.getProxyApi();
    }

    /**
     * Proxy
     *
     * Perform proxy operations.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proxyTest() throws ApiException {
        ProxyRequest proxyRequest = null;
        CompletableFuture<ProxyResponse> response =
        api.proxy(proxyRequest);
        
        // TODO: test validations
    }
    
}
