//
// LeaderboardEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeaderboardEntry: Codable, Hashable {

    /** The rank of the player */
    public var rank: Int
    /** The multiplier to apply to source values received for this product action helper events */
    public var score: Double?
    /** The multiplier to apply to source values received for this product action helper events */
    public var bestScores: [Double]?
    public var members: [LeaderboardMember]

    public init(rank: Int, score: Double? = nil, bestScores: [Double]? = nil, members: [LeaderboardMember]) {
        self.rank = rank
        self.score = score
        self.bestScores = bestScores
        self.members = members
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rank
        case score
        case bestScores
        case members
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rank, forKey: .rank)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(bestScores, forKey: .bestScores)
        try container.encode(members, forKey: .members)
    }
}

