//
// RankingStrategy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RankingStrategy: Codable, Hashable {

    /** scoreDesc - The Ranking that can be Ascending or Descending based on timeDesc. timeDesc - The Ranking that can be Ascending or Descending based on scoreDesc. scoreFirst - The Ranking that can be score first or time first ignoreTime - The Ranking when time is ignored ignoreScore - The Ranking when score is ignored */
    public var constraints: [String]?

    public init(constraints: [String]? = nil) {
        self.constraints = constraints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case constraints
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(constraints, forKey: .constraints)
    }
}

