//
// ScoringStrategy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScoringStrategy: Codable, Hashable {

    /** The scoring strategies types \"SumBest\" value */
    public var limitUpdatesTo: Int?
    /** The scoring strategies types \"LimitedTo\" value */
    public var sumBestXOf: Int?
    /** The scoring strategies types \"FirstTo\" value */
    public var lastUpdateTimeStamp: Int64?
    /** Not supported at the moment */
    public var recordTimeWhenSumReaches: Double?

    public init(limitUpdatesTo: Int? = nil, sumBestXOf: Int? = nil, lastUpdateTimeStamp: Int64? = nil, recordTimeWhenSumReaches: Double? = nil) {
        self.limitUpdatesTo = limitUpdatesTo
        self.sumBestXOf = sumBestXOf
        self.lastUpdateTimeStamp = lastUpdateTimeStamp
        self.recordTimeWhenSumReaches = recordTimeWhenSumReaches
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limitUpdatesTo
        case sumBestXOf
        case lastUpdateTimeStamp
        case recordTimeWhenSumReaches
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(limitUpdatesTo, forKey: .limitUpdatesTo)
        try container.encodeIfPresent(sumBestXOf, forKey: .sumBestXOf)
        try container.encodeIfPresent(lastUpdateTimeStamp, forKey: .lastUpdateTimeStamp)
        try container.encodeIfPresent(recordTimeWhenSumReaches, forKey: .recordTimeWhenSumReaches)
    }
}

