//
// CallbackEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CallbackEntry: Codable, Hashable {

    public var name: String
    public var constraints: [String]

    public init(name: String, constraints: [String]) {
        self.name = name
        self.constraints = constraints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case constraints
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(constraints, forKey: .constraints)
    }
}

