openapi: 3.0.2
info:
  description: "The ZIQNI Member-API is the primary resource used to build services\
    \ and widgets for your members [customers, players, patients, etc]. The service\
    \ is Stomp websokets with SOCK.js even though the system is decribed using OpenApi\
    \ schema for convenience."
  title: ZIQNI Member API
  version: 1.0.0
servers:
- description: Live
  url: https://member-api.ziqni.com
tags:
- description: Perform POST operations on Competitions
  name: competitions
- description: Perform POST operations on Achievements
  name: achievements
- description: Perform POST operations on Contests
  name: contests
- description: Perform POST operations on Messages
  name: messages
- description: Perform POST operations on Rewards
  name: rewards
- description: Perform POST operations on Rules
  name: rules
- description: Perform POST operations on Proxy
  name: proxy
- description: Perform POST operations on Members
  name: members
- description: Perform POST operations on Awards
  name: awards
- description: Perform POST operations on Files
  name: files
paths:
  /member-info:
    description: The endpoint provides information about the member.
    post:
      description: Returns member information for the provided member reference id
      operationId: getMember
      security:
      - OAuth2:
        - ViewMembers
      summary: Get member information by member reference id
      tags:
      - members
      x-ws-only: true
    summary: Member information
  /rewards:
    description: This endpoint is used to perform reward operations.
    post:
      description: This operation support retrieval of rewards for one or many entitites.
      operationId: getRewards
      security:
      - OAuth2:
        - ViewRewards
      summary: Get rewards
      tags:
      - rewards
      x-ws-only: true
    summary: Reward operations
  /rules:
    description: This endpoint is used to perform rules operations.
    post:
      description: This operation support retrieval of rules for one or many entities.
      operationId: getRules
      security:
      - OAuth2:
        - ViewRules
      summary: Get rules
      tags:
      - rules
      x-ws-only: true
    summary: Rules operations
  /achievements:
    description: This endpoint supports member's achievements operation.
    post:
      description: Returns a list of achievements for the provided member ref id and
        applied filters.
      operationId: getAchievements
      security:
      - OAuth2:
        - ViewAchievements
      summary: Get achievements by member reference id
      tags:
      - achievements
      x-ws-only: true
    summary: Member achievements operation
  /awards:
    description: This endpoint is used to perform award operations.
    post:
      description: This operation supports retrieval of awards for one or many entities.
      operationId: getAwards
      security:
      - OAuth2:
        - ViewAwards
      summary: Get awards.
      tags:
      - awards
      x-ws-only: true
    summary: Award operations
  /awards-claim:
    description: This endpoint is used to perform award operations.
    post:
      description: This operation enables a member to claim awards.
      operationId: claimAwards
      security:
      - OAuth2:
        - ClaimAwards
      summary: Claim awards.
      tags:
      - awards
      x-ws-only: true
    summary: Award operations
  /competitions:
    description: This endpoint supports member's competitions operation.
    post:
      description: Returns a list of competitions for the provided member ref id and
        applied filters.
      operationId: getCompetitions
      security:
      - OAuth2:
        - ViewCompetitions
      summary: Get competitions by member reference id
      tags:
      - competitions
      x-ws-only: true
    summary: Member competitions operation
  /contests:
    description: This endpoint supports member's contests operation.
    post:
      description: Returns a list of contests for the provided member ref id and applied
        filters.
      operationId: getContests
      security:
      - OAuth2:
        - ViewContests
      summary: Get contests by member reference Id
      tags:
      - contests
      x-ws-only: true
    summary: Member contests operation
  /files:
    description: This endpoint is used to perform files operations.
    post:
      description: This operation supports retrieval of file objects for one or many
        entities.
      operationId: getFiles
      summary: Get files.
      tags:
      - files
      x-ws-only: true
    summary: Files operations
  /manage-optin:
    description: This endpoint supports member's optin operation.
    post:
      description: Returns a list of member optin information
      operationId: manageOptin
      security:
      - OAuth2:
        - ViewMembers
      summary: Get member optin information
      tags:
      - members
      x-ws-only: true
    summary: Member optin operation
  /leaderboard:
    post:
      callbacks:
        leaderboardUpdate:
          '{$request.body#/id}':
            post:
              operationId: leaderboardUpdate_Post
              x-callback-request: true
      operationId: subscribeToLeaderboard
  /messages:
    description: This endpoint supports member's messages operation.
    post:
      callbacks:
        newMessage:
          '{$request.body#/id}':
            post:
              operationId: newMessage_Post
              x-callback-request: true
      description: Returns a list of messages for the provided member ref id and applied
        filters.
      operationId: getMessages
      security:
      - OAuth2:
        - ViewMessages
      summary: Get messages by member reference id
      tags:
      - messages
      x-ws-only: true
    summary: Member messages operation
  /entity-changes:
    post:
      callbacks:
        entityChanged:
          '{$request.body#/entityType}':
            post:
              operationId: entityChanged_Post
              x-callback-request: true
        entityStateChanged:
          '{$request.body#/entityType}':
            post:
              operationId: entityStateChanged_Post
              x-callback-request: true
      description: subscribes a client to receive out-of-band data
      operationId: subscribeToEntityChanges
      tags:
      - entity-changes
components:
  securitySchemes:
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: https://iam.ziqni.io/oauth/authorize
          scopes:
            ViewContests: Grants read access
            ViewCompetitions: Grants read access
            ViewAchievements: Grants read access
            ViewRewards: Grants read access
            ViewMessages: Grants read access
            ViewAwards: Grants read access
            ViewRules: Grants read access
            ViewMembers: Grants read access
          tokenUrl: https://iam.ziqni.io/oauth/token
      type: oauth2
