name: OpenAPIClient
targets:
  ZiqniMemberSDK:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [ZiqniMemberSDK]
    info:
      path: ./Info.plist
      version: 1.0.8
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
