projectVersion: 0.0.1
licenseName: "Ziqni Commercial License"
projectDescription: "Client library for Ziqni Gamification API"
projectName: "@ziqni-tech/gamification-api-client"
dateLibrary: java8
hideGenerationTimestamp: true
files:
#  AUTHORS.md: {}
#  ws_api_delegate.mustache:
#    templateType: API
#    destinationFilename: WsDelegate.java
#  api_security_roles.mustache:
#    folder: src/main/java/com/ziqni/api/security
#    destinationFilename: SecurityRoles.java
#    templateType: SupportingFiles
#  api.mustache-ignore:
#    templateType: API
#    destinationFilename: Impl.kt
#  other/check.mustache:
#    folder: scripts
#    destinationFilename: check.sh
#    templateType: SupportingFiles

