//
// LeaderboardResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeaderboardResponse: Codable, Hashable {

    public var meta: ResponseMeta
    public var errors: [ModelError]
    public var data: Leaderboard

    public init(meta: ResponseMeta, errors: [ModelError], data: Leaderboard) {
        self.meta = meta
        self.errors = errors
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meta
        case errors
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(meta, forKey: .meta)
        try container.encode(errors, forKey: .errors)
        try container.encode(data, forKey: .data)
    }
}

