//
// CallbacksResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CallbacksResponse: Codable, Hashable {

    public var callback: [CallbackEntry]

    public init(callback: [CallbackEntry]) {
        self.callback = callback
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case callback
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callback, forKey: .callback)
    }
}

