//
// ContestFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Filter to trim results from list of Contets */
public struct ContestFilter: Codable, Hashable {

    public var productIds: [String]?
    public var tags: [String]?
    public var startDate: DateRange?
    public var endDate: DateRange?
    public var sortBy: [QuerySortBy]?
    public var ids: [String]?
    public var competitionIds: [String]?
    public var skip: Int?
    public var limit: Int?
    public var statusCode: NumberRange?
    /** Specify the constraints that need to be applied to the filter. */
    public var constraints: [String]?

    public init(productIds: [String]? = nil, tags: [String]? = nil, startDate: DateRange? = nil, endDate: DateRange? = nil, sortBy: [QuerySortBy]? = nil, ids: [String]? = nil, competitionIds: [String]? = nil, skip: Int? = nil, limit: Int? = nil, statusCode: NumberRange? = nil, constraints: [String]? = nil) {
        self.productIds = productIds
        self.tags = tags
        self.startDate = startDate
        self.endDate = endDate
        self.sortBy = sortBy
        self.ids = ids
        self.competitionIds = competitionIds
        self.skip = skip
        self.limit = limit
        self.statusCode = statusCode
        self.constraints = constraints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productIds
        case tags
        case startDate
        case endDate
        case sortBy
        case ids
        case competitionIds
        case skip
        case limit
        case statusCode
        case constraints
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productIds, forKey: .productIds)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(sortBy, forKey: .sortBy)
        try container.encodeIfPresent(ids, forKey: .ids)
        try container.encodeIfPresent(competitionIds, forKey: .competitionIds)
        try container.encodeIfPresent(skip, forKey: .skip)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(constraints, forKey: .constraints)
    }
}

