//
// ProductReduced.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductReduced: Codable, Hashable {

    /** The name of the product */
    public var name: String?
    /** The reference to this product in your system. The reference identifier can not be changed after the product has been created */
    public var productRefId: String?
    public var customFields: [String: AnyCodable]?
    /** A list of id's used to tag models */
    public var tags: [String]?
    public var metadata: [String: String]?

    public init(name: String? = nil, productRefId: String? = nil, customFields: [String: AnyCodable]? = nil, tags: [String]? = nil, metadata: [String: String]? = nil) {
        self.name = name
        self.productRefId = productRefId
        self.customFields = customFields
        self.tags = tags
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case productRefId
        case customFields
        case tags
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(productRefId, forKey: .productRefId)
        try container.encodeIfPresent(customFields, forKey: .customFields)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

